VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Logger_ILogWriter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' Logger_ILogWriter.cls
Option Explicit

Public Sub Initialize()
End Sub

Public Sub WriteLog(logInfo As Logger_LogInfoStruct)
End Sub

Public Sub Terminate()
End Sub
