@startuml クラス図
' Updated class diagram to match current code structure

package UserInterface {
    class Logger_Provider << (M,66CCFF) Module >> #LightBlue ##black {
        + MyLogger() : Logger_Facade
    }
    class Logger_SingletonManager << (M,66CCFF) Module >> #LightBlue ##black {
        - mLogger As Logger_Facade
        + GetMyLogger() : Logger_Facade
        + ReleaseMyLogger()
    }
}

class Logger_Facade {
    + Initialize() : Logger_ConfigBuilder
    + Log(Message, LoggerLogTag)
    + Terminate()
    + UsingTracer(ModuleName, ProcName) : Logger_ProcedureTracer
    ~ EnterProcedureContext()
    ~ ExitProcedureContext()
    + Reset()
}

class Logger_Controller {
    - Collection of Logger_ILogWriter
    + Initialize(LoggerConfigStruct)
    + WriteLog(LoggerLogInfoStruct)
    + EnterProcedureContext()
    + ExitProcedureContext()
    + Terminate()
}

interface Logger_ILogWriter {
    + Initialize()
    + WriteLog(LoggerLogInfoStruct)
    + Terminate()
}

class Logger_MetadataProvider {
    + EnrichLogEntry(LoggerLogInfoStruct)
}

class Logger_ProcedureTracer {
    + Init(ModuleName, ProcName)
    + Class_Terminate()
}

package Builders {
    class Logger_ConfigBuilder {
        + DisableLogging() : Logger_ConfigBuilder
        + EnableTagFiltering() : Logger_TagFilterBuilder
        + EnableStackTrace() : Logger_ConfigBuilder
        + DisableWriteToImmediate() : Logger_ConfigBuilder
        + EnableWriteToExcelSheet() : Logger_ExcelOutputBuilder
        + Build()
    }
    class Logger_TagFilterBuilder {
        + Add(tag As LoggerLogTag) : Logger_TagFilterBuilder
        + Apply() : Logger_ConfigBuilder
    }
    class Logger_ExcelOutputBuilder {
        + SetOutputExcelSheet(sheet As Worksheet) : Logger_ConfigBuilder
    }
}

package "Log Writers" {
    class Logger_Writer_Excel {
    }
    class Logger_Writer_Immediate {
    }
}

package "Data Structures (Type / Enum)" {
    struct LoggerConfigStruct << (T,FFFFCC) Type >>
    struct LoggerLogInfoStruct << (T,FFFFCC) Type >>
    enum LoggerLogTag
}

' --- Relationships ---
Logger_Provider --> Logger_SingletonManager : uses >
Logger_SingletonManager --> Logger_Facade : provides >
Logger_Facade --> Logger_Controller : uses >
Logger_Facade --> Logger_ProcedureTracer : creates >
Logger_Facade --> Logger_ConfigBuilder : returns >
Logger_Controller --> Logger_MetadataProvider : uses >
Logger_Controller o--> "*" Logger_ILogWriter : holds collection
Logger_ILogWriter <|.. Logger_Writer_Excel
Logger_ILogWriter <|.. Logger_Writer_Immediate
Logger_ConfigBuilder --> Logger_Controller : configures >
Logger_TagFilterBuilder --> Logger_ConfigBuilder : returns >
Logger_ExcelOutputBuilder --> Logger_ConfigBuilder : returns >
Logger_ProcedureTracer --> Logger_Facade : uses >

@enduml